name: golang
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Login Docker.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: docker.io
        username: ${{ secrets.ROBOT_USER_DOCKERHUB }}
        password: ${{ secrets.ROBOT_TOKEN_DOCKERHUB }}

    - name: Login Quay.io
      uses: docker/login-action@v1
      with:
        logout: true
        registry: quay.io
        username: ${{ secrets.ROBOT_USER_QUAY }}
        password: ${{ secrets.ROBOT_TOKEN_QUAY }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Build Image 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}
          docker.io/${{ secrets.GIT_PROJECT }}/${{ github.workflow }}:main-${{ github.sha }}
