name: UBI8ImageBuild
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker.io + Quay.io Login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin quay.io; \
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin docker.io 
    - name: Build Image ccio-gotools
      run: |
        docker build . --file ./Dockerfile \
            --tag quay.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang \
            --tag docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang \
            --tag quay.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang:ubi \
            --tag docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang:ubi
    - name: Push containercraft/gotools
      run: |
        docker push quay.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang; \
        docker push docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang; \
        docker push quay.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang:ubi; \
        docker push docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/golang:ubi;
